import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import * as React from "react";

import Hamburger from "../components/Hamburger";

export default function Home() {
  React.useEffect(() => {
    document.documentElement.style.height = "100%";
    document.documentElement.style.display = "flex";
    document.documentElement.style.flexDirection = "column";
    document.documentElement.style.justifyContent = "center";
    document.documentElement.style.alignItems = "center";
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello world
        </h1>
        <Hamburger></Hamburger>
      </main>

      <footer className={styles.footer}>
        this is footer
      </footer>
    </div>
  );
}
