import { Fira_Code } from "next/font/google";
import { make as AlignCenter } from "@/views/shared/AlignCenter.mjs";
import { make as NavigationBar } from "@/views/shared/NavigationBar.mjs";
import { make as AppFooter } from "@/views/shared/AppFooter.mjs";

const font = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AlignCenter>
          <>
            <NavigationBar />
            {children}
            <AppFooter />
          </>
        </AlignCenter>
      </body>
    </html>
  );
}
